-- CTO HANDOVER: SUPABASE SETUP SCRIPT
-- RUN THIS IN THE SUPABASE SQL EDITOR

-- 1. ENABLE EXTENSIONS (If not already)
create extension if not exists "uuid-ossp";

-- 2. AUTH TRIGGERS: Sync auth.users to public.users
-- This ensures that when a user signs up via Supabase Auth, they exist in our public table.
-- Note: Our API handles this manually for now to set roles, but this is a safety net.
-- Actually, the Prompt requested: "SQL to automatically insert a new user... whenever they sign up"
-- Since our API does it, we should be careful not to duplicate.
-- However, standard practice is a trigger. Let's make it safe (ON CONFLICT DO NOTHING).

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'STUDENT') -- Default to STUDENT if unknown
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger logic
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- Enable RLS on tables
alter table public.users enable row level security;
alter table public.classes enable row level security;
alter table public.work_sessions enable row level security;
alter table public.submissions enable row level security;

-- USERS: Users can read their own data
create policy "Users can view own data" on public.users
  for select using (auth.uid()::text = id);

-- CLASSES: Lecturers see their own classes. Students see classes they submit to?
-- Simplified: Lecturers see their own.
create policy "Lecturers see own classes" on public.classes
  for all using (auth.uid()::text = lecturer_id);

-- WORK SESSIONS:
-- Lecturers see own.
create policy "Lecturers see own sessions" on public.work_sessions
  for all using (auth.uid()::text = lecturer_id);

-- Students need to READ work sessions to validate codes.
-- Ideally, we'd check if they have the code, but RLS is row-based.
-- For now, allow Authenticated users to READ work sessions (Public metadata).
create policy "Authenticated users can read sessions" on public.work_sessions
  for select using (auth.role() = 'authenticated');

-- SUBMISSIONS:
-- Students see their own.
create policy "Students see own submissions" on public.submissions
  for select using (auth.uid()::text = user_id);

-- Students can insert their own.
create policy "Students can submit" on public.submissions
  for insert with check (auth.uid()::text = user_id);

-- Lecturers see submissions for their work sessions.
-- Complex join required? RLS doesn't like complex joins for performance.
-- Alternative: We rely on API logic for complex access.
-- But for strict RLS:
create policy "Lecturers see submissions for their sessions" on public.submissions
  for select using (
    exists (
      select 1 from public.work_sessions
      where work_sessions.id = submissions.work_session_id
      and work_sessions.lecturer_id = auth.uid()::text
    )
  );

-- 4. STORAGE BUCKETS
-- Create 'submissions' bucket if not exists
insert into storage.buckets (id, name, public)
values ('submissions', 'submissions', false)
on conflict (id) do nothing;

-- Policy: Authenticated users can upload to submissions
create policy "Authenticated users can upload submissions"
on storage.objects for insert
with check (
  bucket_id = 'submissions'
  and auth.role() = 'authenticated'
);

-- Policy: Users can read their own uploads (if path contains their ID? or just generic?)
-- For now, allow creators to read.
create policy "Users can read own uploads"
on storage.objects for select
using (
  bucket_id = 'submissions'
  and auth.uid() = owner
);

-- Policy: Lecturers can read all (Simulated via Service Role in API, but for direct access:)
-- Hard to distinguish "Lecturer" in storage policies without custom claims.
-- Taking "Zero Trust" literally -> API should sign URLs.
-- So we keep the bucket PRIVATE (public = false) and rely on Signed URLs generated by the Backend.
