import { prisma } from '@/lib/prisma';
import OpenAI from 'openai';
import { extractPagesMultimodal, ocrDocument } from '@/lib/ai/gemini';
import { readFile } from '@/lib/storage';
import pLimit from 'p-limit';

// Universal Retry Wrapper
async function withRetries<T>(fn: () => Promise<T>, retries = 3, delayMs = 3000): Promise<T> {
    for (let i = 0; i < retries; i++) {
        try { return await fn(); } catch (error: any) {
            console.warn(`[NETWORK RETRY] Operation failed: ${error.message}. Retrying...`);
            if (i === retries - 1) throw error;
            await new Promise(res => setTimeout(res, delayMs));
        }
    }
    throw new Error("Unreachable");
}

const deepSeekClient = new OpenAI({
    baseURL: process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com/v1',
    apiKey: process.env.DEEPSEEK_API_KEY || 'dummy',
    timeout: 300000,
    maxRetries: 4,
});

export async function handleAiGrade(job: any) {
    console.log(`[WORKER] Booting ATOMIC Map-Reduce for Job ${job.id}`);

    let submissionIdToUpdate: string | null = null;

    try {
        const rawPayload = typeof job.payload === 'string' ? JSON.parse(job.payload) : job.payload;
        // Unwrap the nested payload from QStash if it exists, otherwise use raw
        const actualPayload = rawPayload.payload ? rawPayload.payload : rawPayload;

        submissionIdToUpdate = actualPayload.submissionId;

        if (!submissionIdToUpdate) throw new Error("Payload is missing submissionId");

        const submission = await prisma.submission.findUnique({
            where: { id: submissionIdToUpdate },
            include: { workSession: true }
        });

        if (!submission) throw new Error("Submission not found");

        let finalRubricText = submission.workSession.rubric;

        // 1. CACHE RUBRIC
        if ((!finalRubricText || finalRubricText.trim() === '') && submission.workSession.markingScheme) {
            console.log("[WORKER] Extracting Rubric from PDF...");
            const urlOrText = submission.workSession.markingScheme;
            if (urlOrText.includes('/') || urlOrText.toLowerCase().endsWith('.pdf') || urlOrText.toLowerCase().endsWith('.png')) {
                const buffer = await withRetries(() => readFile(urlOrText, 'exam_pdfs'));
                if (urlOrText.toLowerCase().endsWith('.pdf')) {
                    const pages = await withRetries(() => extractPagesMultimodal(buffer));
                    finalRubricText = pages.map(p => p.text).join('\n\n');
                } else {
                    const mimeType = urlOrText.toLowerCase().endsWith('.png') ? 'image/png' : 'application/pdf';
                    finalRubricText = await withRetries(() => ocrDocument(buffer, mimeType));
                }
            } else {
                finalRubricText = urlOrText;
            }
            await prisma.workSession.update({
                where: { id: submission.workSession.id },
                data: { rubric: finalRubricText }
            });
        }

        if (!finalRubricText || finalRubricText.trim() === '') throw new Error("Fatal: Rubric text is entirely missing.");

        // 2. MAP PHASE: Read OCR Text generated by ocr/route.ts
        let fullExamText = "";
        let detectedRegNo = "UNKNOWN";

        const sortedData = (submission.extractedData as any[]).sort((a, b) => a.pages[0] - b.pages[0]);
        for (const chunk of sortedData) {
            try {
                const parsed = JSON.parse(chunk.text);
                if (parsed.registration_number && parsed.registration_number !== "UNKNOWN") {
                    detectedRegNo = parsed.registration_number;
                }
                fullExamText += "\n\n" + (parsed.full_text || "");
            } catch {
                fullExamText += "\n\n" + chunk.text;
            }
        }
        if (!fullExamText.trim()) fullExamText = "No readable text extracted.";

        // 3. SEGMENT RUBRIC
        const rubricParseResponse = await deepSeekClient.chat.completions.create({
            model: "deepseek-chat",
            messages: [
                { role: "system", content: `Parse this Marking Scheme into a JSON array: { "rubric": [ { "question": "Q1", "rubric_segment": "criteria text", "max_score": 10 } ] }` },
                { role: "user", content: finalRubricText }
            ],
            response_format: { type: "json_object" },
            temperature: 0.1,
        });

        let parsedRubricMap: any[] = [];
        try {
            const raw = rubricParseResponse.choices[0]?.message?.content || '{"rubric":[]}';
            const clean = raw.replace(/```json/g, '').replace(/```/g, '').trim();
            parsedRubricMap = JSON.parse(clean).rubric || [];
        } catch (e) {
            parsedRubricMap = [{ question: "Global", rubric_segment: finalRubricText, max_score: 100 }];
        }

        // 4. ATOMIC GRADING (pLimit)
        console.log(`[WORKER] Initiating Atomic Grading for ${parsedRubricMap.length} Questions...`);
        const limit = pLimit(10);

        const atomicGradingPromises = parsedRubricMap.map((rubricItem: any) =>
            limit(async () => {
                try {
                    const response = await deepSeekClient.chat.completions.create({
                        model: "deepseek-chat",
                        messages: [
                            { role: "system", content: `You are an empathetic professor. Grade ONE question against ONE rubric segment.
RULES:
1. SEMANTIC MATCH: Grade based on MEANING, not exact words. Award marks for core concepts.
2. EMPATHY: Always seek reasons to give points. Use [Partial Match] for incomplete but relevant answers.
3. BREVITY: Keep feedback to MAX 1-2 short sentences BUT BE ACCURATE,AND CONCISE.
4. TIERS: Start feedback with [Exact Match], [Partial Match], [Out of Scope], or [Missing].
5. MATH/DIAGRAMS: Award full/partial marks based on text explanation; ignore OCR's inability to see sketches.

JSON: { "extracted_evidence": "short quote", "score": number, "feedback": "tier + short explanation" }` },
                            { role: "user", content: `QUESTION: ${rubricItem.question}\nMAX SCORE: ${rubricItem.max_score}\n\nRUBRIC SEGMENT:\n${rubricItem.rubric_segment}\n\nSTUDENT ANSWER (FULL TEXT):\n${fullExamText}` }
                        ],
                        response_format: { type: "json_object" },
                        temperature: 0.1,
                    });

                    const raw = response.choices[0]?.message?.content || '{}';
                    const clean = raw.replace(/```json/g, '').replace(/```/g, '').trim();
                    const result = JSON.parse(clean);

                    return {
                        question: rubricItem.question,
                        score: Number(result.score) || 0,
                        max: Number(rubricItem.max_score) || 0,
                        feedback: result.feedback || "No feedback provided.",
                        evidenceSnippet: result.extracted_evidence || "None found"
                    };
                } catch (e: any) {
                    throw new Error("Engine failed: " + e.message);
                }
            })
        );

        const formattedBreakdown = await Promise.all(atomicGradingPromises);

        // 5. SAVE TO DB
        if (formattedBreakdown.some((item: any) => item.feedback?.includes("Engine failed"))) {
            throw new Error("Engine failed during grading process. Aborting save.");
        }

        const calculatedTotalScore = formattedBreakdown.reduce((sum: number, item: any) => sum + item.score, 0);

        await prisma.score.upsert({
            where: { submissionId: submission.id },
            update: {
                totalMarks: calculatedTotalScore,
                remarks: "Assessment complete. Please review your specific feedback below.",
                breakdown: JSON.stringify(formattedBreakdown),
                detectedIdentity: detectedRegNo
            },
            create: {
                submissionId: submission.id,
                totalMarks: calculatedTotalScore,
                remarks: "Assessment complete. Please review your specific feedback below.",
                breakdown: JSON.stringify(formattedBreakdown),
                detectedIdentity: detectedRegNo
            }
        });

        await prisma.submission.update({
            where: { id: submission.id },
            data: { status: 'GRADED', studentRegNo: detectedRegNo !== "UNKNOWN" ? detectedRegNo : submission.studentRegNo }
        });

        let calculatedTotalScoreLog = calculatedTotalScore; // Fix variable scope for logging
        console.log(`[WORKER] Mission Accomplished for Submission ${submission.id}. Score: ${calculatedTotalScoreLog}`);

    } catch (fatalError: any) {
        console.error(`[WORKER] Error:`, fatalError.message);
        if (submissionIdToUpdate) {
            await prisma.submission.update({
                where: { id: submissionIdToUpdate },
                data: { status: 'FAILED', feedback: fatalError.message }
            }).catch(e => console.error("Failed to update status to FAILED", e));
        }
        throw fatalError;
    }
}