import { prisma } from '@/lib/prisma';
import OpenAI from 'openai';
import { extractPagesMultimodal, ocrDocument } from '@/lib/ai/gemini';
import { readFile } from '@/lib/storage';
import pLimit from 'p-limit';

// Universal Retry Wrapper
async function withRetries<T>(fn: () => Promise<T>, retries = 3, delayMs = 3000): Promise<T> {
    for (let i = 0; i < retries; i++) {
        try { return await fn(); } catch (error: any) {
            console.warn(`[NETWORK RETRY] Operation failed: ${error.message}. Retrying...`);
            if (i === retries - 1) throw error;
            await new Promise(res => setTimeout(res, delayMs));
        }
    }
    throw new Error("Unreachable");
}

const deepSeekClient = new OpenAI({
    baseURL: process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com/v1',
    apiKey: process.env.DEEPSEEK_API_KEY || 'dummy',
    timeout: 300000,
    maxRetries: 4,
});

export async function handleAiGrade(job: any) {
    console.log(`[WORKER] Booting ATOMIC Map-Reduce for Job ${job.id}`);

    let submissionIdToUpdate: string | null = null;

    try {
        const rawPayload = typeof job.payload === 'string' ? JSON.parse(job.payload) : job.payload;
        // Unwrap the nested payload from QStash if it exists, otherwise use raw
        const actualPayload = rawPayload.payload ? rawPayload.payload : rawPayload;

        submissionIdToUpdate = actualPayload.submissionId;

        if (!submissionIdToUpdate) throw new Error("Payload is missing submissionId");

        const submission = await prisma.submission.findUnique({
            where: { id: submissionIdToUpdate },
            include: { workSession: true }
        });

        if (!submission) throw new Error("Submission not found");

        let finalRubricText = submission.workSession.rubric;

        // 1. CACHE RUBRIC
        if ((!finalRubricText || finalRubricText.trim() === '') && submission.workSession.markingScheme) {
            console.log("[WORKER] Extracting Rubric from PDF...");
            const urlOrText = submission.workSession.markingScheme;
            if (urlOrText.includes('/') || urlOrText.toLowerCase().endsWith('.pdf') || urlOrText.toLowerCase().endsWith('.png')) {
                const buffer = await withRetries(() => readFile(urlOrText, 'exam_pdfs'));
                if (urlOrText.toLowerCase().endsWith('.pdf')) {
                    const pages = await withRetries(() => extractPagesMultimodal(buffer));
                    finalRubricText = pages.map(p => p.text).join('\n\n');
                } else {
                    const mimeType = urlOrText.toLowerCase().endsWith('.png') ? 'image/png' : 'application/pdf';
                    finalRubricText = await withRetries(() => ocrDocument(buffer, mimeType));
                }
            } else {
                finalRubricText = urlOrText;
            }
            await prisma.workSession.update({
                where: { id: submission.workSession.id },
                data: { rubric: finalRubricText }
            });
        }

        if (!finalRubricText || finalRubricText.trim() === '') throw new Error("Fatal: Rubric text is entirely missing.");

        // 2. MAP PHASE: Read OCR Text generated by ocr/route.ts
        let fullExamText = "";
        let detectedRegNo = "UNKNOWN";

        const sortedData = (submission.extractedData as any[]).sort((a, b) => a.pages[0] - b.pages[0]);
        for (const chunk of sortedData) {
            try {
                const parsed = JSON.parse(chunk.text);
                if (parsed.registration_number && parsed.registration_number !== "UNKNOWN") {
                    detectedRegNo = parsed.registration_number;
                }
                fullExamText += "\n\n" + (parsed.full_text || "");
            } catch {
                fullExamText += "\n\n" + chunk.text;
            }
        }
        if (!fullExamText.trim()) fullExamText = "No readable text extracted.";

        // 3. PROGRAMMATIC RUBRIC PARSER (Fix 6/0 bug permanently)
        // Never rely on LLM to guess max scores. Extract it strictly via Regex.
        // Assuming rubric lines look like "Q1: Explain photosynthesis (5 marks) \n criteria..."
        console.log("[WORKER] Programmatically extracting max scores from rubric...");
        const masterRubricArray: any[] = [];
        const rubricLines = finalRubricText.split('\n');
        let currentQ = "Global";
        let currentMax = 100;
        let currentSegment = "";

        const qRegex = /^(?:Q(?:uestion)?\s*|)(\d+[a-zA-Z]*(?:\.[a-z]+|\([a-z]+\))?)/i;
        const markRegex = /\(\s*(\d+)\s*marks?\s*\)/i; // Matches "( 5 marks )"

        for (const line of rubricLines) {
            const qMatch = line.match(qRegex);
            const markMatch = line.match(markRegex);

            if (qMatch && line.length < 100) {
                // Save previous
                if (currentSegment) {
                    masterRubricArray.push({ question: currentQ, rubric_segment: currentSegment.trim(), max_score: currentMax });
                }
                currentQ = qMatch[1].toUpperCase();
                currentMax = markMatch ? parseInt(markMatch[1]) : 0;
                currentSegment = line;
            } else {
                currentSegment += "\n" + line;
                if (markMatch && currentMax === 0) {
                    currentMax = parseInt(markMatch[1]);
                }
            }
        }
        if (currentSegment) {
            masterRubricArray.push({ question: currentQ, rubric_segment: currentSegment.trim(), max_score: currentMax });
        }

        // Fuzzy matcher helper
        const normalizeId = (id: string) => (id || "").replace(/[^a-zA-Z0-9]/g, '').toUpperCase();

        // 4. ATOMIC GRADING (pLimit)
        console.log(`[WORKER] Initiating Atomic Grading for ${masterRubricArray.length} Questions...`);
        const pLimit = (await import('p-limit')).default;
        const limit = pLimit(10);

        const atomicGradingPromises = masterRubricArray.map((rubricItem: any) =>
            limit(async () => {
                try {
                    const response = await deepSeekClient.chat.completions.create({
                        model: "deepseek-chat",
                        messages: [
                            { role: "system", content: `You are a grader. Evaluate ONE question against ONE rubric segment.
MANDATORY DIRECTIVES:
1. Extract exact evidence first.
2. Start feedback with [Exact Match], [Partial Match], [Out of Scope], or [Missing].
3. DO NOT penalize for missing sketches/diagrams as OCR cannot read them.
JSON FORMAT: { "extracted_evidence": "quote", "score": number, "feedback": "tier + max 3 sentences" }` },
                            { role: "user", content: `QUESTION: ${rubricItem.question}\nMAX SCORE: ${rubricItem.max_score}\n\nRUBRIC SEGMENT:\n${rubricItem.rubric_segment}\n\nSTUDENT ANSWER (FULL TEXT):\n${fullExamText}` }
                        ],
                        response_format: { type: "json_object" },
                        temperature: 0.1,
                    });

                    const raw = response.choices[0]?.message?.content || '{}';
                    const clean = raw.replace(/```json/g, '').replace(/```/g, '').trim();
                    const result = JSON.parse(clean);

                    return {
                        question: rubricItem.question,
                        score: Number(result.score) || 0,
                        max: Number(rubricItem.max_score) || 0,
                        feedback: result.feedback || "No feedback provided.",
                        evidenceSnippet: result.extracted_evidence || "None found"
                    };
                } catch (e) {
                    return { question: rubricItem.question, score: 0, max: Number(rubricItem.max_score) || 0, feedback: "[Out of Scope] Engine failed.", evidenceSnippet: "ERROR" };
                }
            })
        );

        const formattedBreakdown = await Promise.all(atomicGradingPromises);

        // 5. SAVE TO DB (IDEMPOTENT)
        const calculatedTotalScore = formattedBreakdown.reduce((sum: number, item: any) => sum + item.score, 0);

        await prisma.score.upsert({
            where: { submissionId: submission.id },
            update: {
                totalMarks: calculatedTotalScore,
                remarks: "Graded via Atomic Map-Reduce.",
                breakdown: JSON.stringify(formattedBreakdown),
                detectedIdentity: detectedRegNo
            },
            create: {
                submissionId: submission.id,
                totalMarks: calculatedTotalScore,
                remarks: "Graded via Atomic Map-Reduce.",
                breakdown: JSON.stringify(formattedBreakdown),
                detectedIdentity: detectedRegNo
            }
        });

        await prisma.submission.update({
            where: { id: submission.id },
            data: { status: 'GRADED', studentRegNo: detectedRegNo !== "UNKNOWN" ? detectedRegNo : submission.studentRegNo }
        });

        let calculatedTotalScoreLog = calculatedTotalScore; // Fix variable scope for logging
        console.log(`[WORKER] Mission Accomplished for Submission ${submission.id}. Score: ${calculatedTotalScoreLog}`);

    } catch (fatalError: any) {
        console.error(`[WORKER] Error:`, fatalError.message);
        if (submissionIdToUpdate) {
            await prisma.submission.update({
                where: { id: submissionIdToUpdate },
                data: { status: 'FAILED', feedback: fatalError.message }
            }).catch(e => console.error("Failed to update status to FAILED", e));
        }
        throw fatalError;
    }
}