'use server';

import { db } from "@/lib/db";
import { ReleaseMode, SubmissionStatus } from "@prisma/client";

/**
 * Processes a submission in the background, simulating AI grading.
 * @param submissionId The ID of the submission to process.
 */
export async function processSubmission(submissionId: string) {
  try {
    // 1. Update status to PROCESSING to give immediate UI feedback
    await db.submission.update({
      where: { id: submissionId },
      data: { status: SubmissionStatus.PROCESSING },
    });

    // 2. Simulate the AI grading delay
    await new Promise(r => setTimeout(r, 2000));

    // 3. Fetch the submission and its parent WorkSession to check settings
    const submission = await db.submission.findUnique({
      where: { id: submissionId },
      include: {
        workSession: true,
      },
    });

    if (!submission || !submission.workSession) {
      throw new Error("Submission or Work Session not found.");
    }

    const { workSession } = submission;

    // 4. Generate a mock score and breakdown
    const mockScore = Math.floor(Math.random() * (95 - 65 + 1) + 65); // Random score between 65 and 95
    const mockBreakdown = [
      { "label": "Question 1", "score": Math.floor(mockScore / 2), "max": 50, "feedback": "Good start." },
      { "label": "Question 2", "score": Math.ceil(mockScore / 2), "max": 50, "feedback": "Could be more detailed." },
    ];
    const mockConfidence = Math.floor(Math.random() * (100 - 80 + 1) + 80); // Random confidence between 80-100%

    // 5. Determine the final status based on the release mode
    let finalStatus: SubmissionStatus;
    if (workSession.releaseMode === ReleaseMode.IMMEDIATE) {
      finalStatus = SubmissionStatus.RELEASED;
    } else { // MANUAL or ON_DEADLINE
      finalStatus = SubmissionStatus.GRADED;
    }
    
    // 6. Create the Score record and update the Submission in a transaction
    await db.$transaction(async (prisma) => {
        // Create the score
        const newScore = await prisma.score.create({
            data: {
                submissionId: submissionId,
                totalMarks: mockScore,
                breakdown: mockBreakdown,
                confidenceScore: mockConfidence,
                isEdited: false,
                remarks: "This score was automatically generated by Playbook AI.",
            },
        });

        // Update the submission with the final status and link the score
        await prisma.submission.update({
            where: { id: submissionId },
            data: {
                status: finalStatus,
                scoreId: newScore.id, 
                confidenceScore: mockConfidence,
            },
        });
    });

  } catch (error) {
    console.error(`Failed to process submission ${submissionId}:`, error);
    // If something fails, mark the submission as FAILED
    await db.submission.update({
      where: { id: submissionId },
      data: { 
          status: SubmissionStatus.FAILED,
          feedback: JSON.stringify({ error: (error as Error).message })
      },
    });
  }
}
